import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import Image from 'next/image';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Rest client app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="flex flex-col flex-grow justify-start self-center items-center pt-[56px]">
          {children}
        </main>
        <footer className="flex justify-between items-end p-2">
          <a
            href="https://github.com/woodo01/graphiql-app"
            target="_blank"
            rel="noreferrer"
          >
            Github Profile
          </a>
          <p>| 2025 |</p>
          <a
            href="https://rs.school/courses/reactjs"
            target="_blank"
            rel="noreferrer"
          >
            <Image
              src="/rss-logo.svg"
              alt="Rolling Scopes Logo"
              width={45}
              height={45}
            ></Image>
          </a>
        </footer>
      </body>
    </html>
  );
}
