import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/app/[locale]/components/layout/Header';
import Footer from '@/app/[locale]/components/layout/Footer';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Rest client app',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): Promise<JSX.Element> {
  const messages = await getMessages();

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang="en">
        <body
          className={`min-h-screen flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          <main className="flex-1 pt-[56px]">{children}</main>
          <Footer />
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
